# see https://docs.codecov.io/docs/codecovyml-reference for more options

coverage:
  status:
    project:                   # measuring the overall project coverage
      default:                 # context, you can create multiple ones with custom titles
        target: 90%            # specify the target coverage for each commit status
        threshold: 1%          # allowed to drop X% and still result in a "success" commit status

    patch:                     # pull requests only: this commit status will measure the
      default:
        target: 60%            # specify the target "X%" coverage to hit
        threshold: 2%          # allowed to drop X% and still result in a "success" commit status

comment: false                 # to disable comments

ignore:
  - "app/services/rescue_from_unless_local.rb"
