sudo: false
dist: trusty
language: ruby
rvm: 2.6.6
cache: bundler
bundler_args: --retry=6
services:
addons:
branches:
  only:
    - master
    - /^int-.*$/
    - /^release-.*$/
script:
  - bundle exec rake spec
before_script:
  - cp -n config/secrets.yml.example config/secrets.yml
before_install:
  - gem install bundler
