# using version 2 because we have to match the kafka one
version: "2"
services:
  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "3001:3001"
    command: bash -c "rm -f tmp/pids/server.pid && bin/rake setup && bin/rake about && bin/rails server -b '0.0.0.0' -p 3001"
    stdin_open: true  # allow for debugger
    tty: true         # interaction
    volumes:
      - ..:/code
      - /code/tmp
      - /code/log
