topics: [
  {
    name: 'nudged',
    schemas: [
        'org.openstax.ec.nudged_v1'
    ],
    config: {
      replication: 3,
      partitions: 3
    }
  },
  {
    name: 'accessed_studyguide',
    schemas: [
        'org.openstax.ec.accessed_studyguide_v1'
    ],
    config: {
      replication: 3,
      partitions: 3
    }
  },
  {
    name: 'created_highlight',
    schemas: [
        'org.openstax.ec.created_highlight_v1',
        'org.openstax.ec.created_highlight_v2'
    ],
    config: {
      replication: 3,
      partitions: 3
    }
  },
  {
    name: 'started_session',
    schemas: [
        'org.openstax.ec.started_session_v1'
    ],
    config: {
      replication: 3,
      partitions: 3
    }
  },
  {
    name: 'changed_state',
    schemas: [
        'org.openstax.ec.changed_state_v1'
    ],
    config: {
      replication: 3,
      partitions: 3
    }
  },
  {
    name: 'interacted_element',
    schemas: [
        'org.openstax.ec.interacted_element_v1'
    ],
    config: {
      replication: 3,
      partitions: 3
    }
  }
]
